import React, {useState} from 'react';
import './style.css'; 
import imgRegion from'../Southern region of Brazil.png'
import pr from'../State of Paraná.png'
import sc from'../State of Santa Catarina.png'
import rs from'../State of Rio Grande do Sul.png'

//Importar api para fazer uma chamada, get, post, put, delete ...
//import mapGeral from '../map.png'

function MenuBar() {

  const [region, setRegion] = useState('desc');

  const changeScreen = (operacao) => {
    switch (operacao) {
      case 'region':
        setRegion('region');
        break;
      case 'pr':
        setRegion('pr');
        break;
      case 'sc':
        setRegion('sc');
        break;
      case 'rs':
        setRegion('rs');
        break;
      case 'desc':
        setRegion('desc');
         break;
      default:
        break;
    }
  };


  return (
    <>
    <div className="menu-bar">
      <ul>
        <li onClick={()=>changeScreen('desc')}><p>Description</p></li>
        <li onClick={()=>changeScreen('region')}><p>South Region Brazil</p></li>
        <li onClick={()=>changeScreen('pr')}><p>Paraná</p></li>
        <li onClick={()=>changeScreen('sc')}><p>Santa Catarina</p></li>
        <li onClick={()=>changeScreen('rs')}><p>Rio Grande do Sul</p></li>
        
      </ul>
    </div>

    <div style={region === "desc"?
    {
    width: "70%",
    margin: "0 auto",
    textAlign: "justify",
    paddingTop: "50px",
    }
    :{display:'none'}}>  
    We obtained the dataset from the source <a target="_blanck" href={"http://labren.ccst.inpe.br/atlas_2017.html"}>http://labren.ccst.inpe.br/atlas_2017.html</a>, 
    and then we divided it among the Brazilian states of Paraná, Santa Catarina, and Rio Grande do Sul. 
    In addition to these, we combined them to also generate their graph, thus representing the southern Brazilian region.
    Using the "buildSubset" function, we sliced the original dataset to obtain isolated information as mentioned above, 
    and for this purpose, we used the Python Pandas library. We applied the machine learning algorithm "Kmeans" to 
    divide the plotted map into 5 center points each in order to partition it into equivalent regions. The Matplotlib library is 
    responsible for rendering the graphics using the subsets generated by the Python function. The color gradient indicates areas where 
    the highest and lowest horizontal global irradiation indices occurred in the year 2017.

    </div>



    <div style={region === "region"?{}:{display:'none'}}><img className="imgGrafic" src={imgRegion} alt="" /></div>
    <div style={region === "pr"?{}:{display:'none'}}><img className="imgGrafic" src={pr} alt="" /></div>
    <div style={region === "sc"?{}:{display:'none'}}><img className="imgGrafic" src={sc} alt="" /></div>
    <div style={region === "rs"?{}:{display:'none'}}><img className="imgGrafic" src={rs} alt="" /></div>
    </>
  );
}

export default MenuBar;
